-- Create the transmissions table
create table public.transmissions (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  message text not null,
  type text default 'BROADCAST'::text,
  sender text default 'ADMIN'::text
);

-- Enable Realtime
alter publication supabase_realtime add table public.transmissions;

-- Policies (Optional: Enable RLS for extra security later)
-- For now, we allow public read (so everyone sees it) and only authenticated insert (if we had Auth)
-- But since we are using client-side admin gate, we might need to open insert for now or use a Service Key on the client (risky but fast for this specific request).
-- Better pattern: All inserts allowed, but client filters/validates.

-- Allow public access
alter table public.transmissions enable row level security;

create policy "Enable read access for all users"
  on public.transmissions for select
  using (true);

create policy "Enable insert for all users"
  on public.transmissions for insert
  with check (true);
